# Kubernetes Service for Retrieval-Free Context Compressor
apiVersion: v1
kind: Service
metadata:
  name: retrieval-free
  namespace: retrieval-free
  labels:
    app.kubernetes.io/name: retrieval-free
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: retrieval-free
    app.kubernetes.io/component: application

---
# Load Balancer Service (optional, for external access)
apiVersion: v1
kind: Service
metadata:
  name: retrieval-free-lb
  namespace: retrieval-free
  labels:
    app.kubernetes.io/name: retrieval-free
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: retrieval-free
    app.kubernetes.io/component: application
  
  # Session affinity (optional)
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600